name: 'npm malicious dependencies check'
description: 'Scan your repository for malicious npm dependencies'
author: 'h4sh5'

runs:
  using: "composite"
  steps:  
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: python3 npm_mal_check.py
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}